export const Categories = {
  typ: [
    { id: '1', name: 'bunda', text: 'Bunda' },
    { id: '2', name: 'kabat', text: 'Kabát' },
    { id: '3', name: 'halenka', text: 'Halenka' },
    { id: '4', name: 'kalhoty', text: 'Kalhoty' },
    { id: '5', name: 'kosile', text: 'Košile' },
    { id: '6', name: 'kratasy', text: 'Kraťasy' },
    { id: '7', name: 'sako', text: 'Sako' },
    { id: '8', name: 'saty', text: 'Šaty' },
    { id: '9', name: 'sukne', text: 'Sukně' },
    { id: '10', name: 'svetry', text: 'Svetry' },
    { id: '12', name: 'triko', text: 'Triko' },
    { id: '13', name: 'boty', text: 'Boty' },
    { id: '14', name: 'doplnky', text: 'Doplňky' },
  ],
  styl: [
    { id: '1', name: 'casual', text: 'Casual' },
    { id: '2', name: 'sportovni', text: 'Sportovní' },
    { id: '3', name: 'formalni', text: 'Formální' },
    { id: '4', name: 'spolecenske', text: 'Společenské' },
  ],
  sezona: [
    { id: '1', name: 'jaro', text: 'Jaro' },
    { id: '2', name: 'leto', text: 'Léto' },
    { id: '3', name: 'podzim', text: 'Podzim' },
    { id: '4', name: 'zima', text: 'Zima' },
  ],
  material: [
    { id: '1', name: 'polyester', text: 'Polyester' },
    { id: '2', name: 'plise', text: 'Plisé' },
    { id: '3', name: 'bavlna', text: 'Bavlna' },
    { id: '4', name: 'denim', text: 'Denim' },
    { id: '5', name: 'bukle', text: 'Buklé' },
    { id: '6', name: 'fleece', text: 'Fleece' },
    { id: '7', name: 'krajka', text: 'Krajka' },
    { id: '8', name: 'krep', text: 'Krep' },
    { id: '9', name: 'kuze', text: 'Kůže' },
    { id: '10', name: 'saten', text: 'Satén' },
    { id: '12', name: 'len', text: 'Len' },
    { id: '13', name: 'semis', text: 'Semiš' },
    { id: '14', name: 'sifon', text: 'Šifon' },
    { id: '15', name: 'vlna', text: 'Vlna' },
    { id: '16', name: 'zerzej', text: 'Žerzej' },
  ],
  barva: [
    { id: '1', name: 'bila', text: 'Bílá' },
    { id: '2', name: 'bezova', text: 'Béžová' },
    { id: '3', name: 'hneda', text: 'Hnědá' },
    { id: '4', name: 'cerna', text: 'Černá' },
    { id: '5', name: 'zluta', text: 'Žlutá' },
    { id: '6', name: 'oranzova', text: 'Oranžová' },
    { id: '7', name: 'cervena', text: 'Červená' },
    { id: '8', name: 'ruzova', text: 'Růžová' },
    { id: '9', name: 'fialova', text: 'Fialová' },
    { id: '10', name: 'modra', text: 'Modrá' },
    { id: '11', name: 'zelena', text: 'Zelená' },
    { id: '12', name: 'seda', text: 'Šedá' },
  ],
  odstin: [
    { id: '1', name: 'svetly', text: 'Světlý' },
    { id: '2', name: 'tmavy', text: 'Tmavý' },
    { id: '3', name: 'neutralni', text: 'Neutrální' },
  ],
  vzor: [
    { id: '1', name: 'pruhovane', text: 'Pruhované' },
    { id: '2', name: 'kostkovane', text: 'Kostkované' },
    { id: '3', name: 'puntikovane', text: 'Puntíkované' },
    { id: '4', name: 'zvireci', text: 'Zvířecí' },
    { id: '5', name: 'kvetovane', text: 'Květované' },
    { id: '6', name: 'geometricke', text: 'Geometrické' },
    { id: '7', name: 'abstraktni', text: 'Abstraktní' },
  ],
  strih: [
    { id: '1', name: 'slim', text: 'Slim' },
    { id: '2', name: 'volny', text: 'Volné' },
    { id: '3', name: 'regular', text: 'Regular' },
  ],
  delka: [
    { id: '1', name: 'kratka', text: 'Krátké' },
    { id: '2', name: 'stredni', text: 'Střední' },
    { id: '3', name: 'dlouha', text: 'Dlouhé' },
  ],
};
